language: java

sudo: required

jdk:
  - oraclejdk8
  
script:
  - ./gradlew assemble
  - ./gradlew check -PremoteBuild
  
notifications:
  email:
    recipients:
      - romeara@live.com
    on_success: change
on_failure: always
