language: java

sudo: required

jdk:
  - oraclejdk8
  
script:
  - ./gradlew assemble
  - ./gradlew check -PremoteBuild
  
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  
notifications:
  email:
    recipients:
      - romeara@live.com
    on_success: change
on_failure: always
